--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /
  config:
    allow_periods_in_identifiers: true
    encoding: utf-8
text_extensions:
  - html
  - erb
base_url: http://vikhyat.net