# coding: utf-8

task :default => [:compile_nanoc, :compile_application]

task :compile_nanoc do
  system "
    cd site/ &&
    bundle exec nanoc co &&
    rm -rf ../Output/Vikhyat &&
    cp -R \"output\" \"../Output/Vikhyat\" &&
    cp -R static/* \"../Output/Vikhyat\" &&
    cd ..
  "
end

task :compile_application do
  system "
    rm -rf Output/Application &&
    cp -R Application Output/Application
  "
end

task :clean do
  system "rm -rf Output/ && mkdir Output"
end
